[package]
name = "buzz"
version = "0.1.0"

description = "A simple system tray application for notifying about unseen e-mail"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/buzz"
repository = "https://github.com/jonhoo/buzz.git"

keywords = ["email","cli","systray","notification"]
categories = ["command-line-utilities", "email"]

license = "MIT/Apache-2.0"

[dependencies]
imap = { git = "https://github.com/jonhoo/rust-imap.git", branch = "idle" }
openssl = "0.7.13"
systray = { git = "https://github.com/qdot/systray-rs.git", branch = "linux-core" }
mailparse = "0.5.1"
toml = "0.3.1"
xdg = "2.0.0"
