[package]
name = "buzz"
version = "0.3.0"

description = "A simple system tray application for notifying about unseen e-mail"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/buzz"
repository = "https://github.com/jonhoo/buzz.git"

keywords = ["email","cli","systray","notification"]
categories = ["command-line-utilities", "email"]

license = "MIT/Apache-2.0"

[dependencies]
imap = "0.3.1"
openssl = "0.9.11"
systray = "0.2.0"
mailparse = "0.5.1"
toml = "0.4.0"
xdg = "2.1.0"
notify-rust = "3.3.0"
rayon = "0.7.0"
