[package]
name = "buzz"
version = "1.0.0"

description = "A simple system tray application for notifying about unseen e-mail"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/buzz"
repository = "https://github.com/jonhoo/buzz.git"

keywords = ["email","cli","systray","notification"]
categories = ["command-line-utilities", "email"]

license = "MIT/Apache-2.0"

[dependencies]
imap = "0.3.2"
openssl = "0.9.14"
systray = "0.2.0"
mailparse = "0.5.1"
toml = "0.4.2"
xdg = "2.1.0"
notify-rust = "3.4.0"
rayon = "0.8.2"
